# Read the documentation: https://github.com/hautelook/AliceBundle/blob/v1.4.1/README.md
hautelook_alice:
    fixtures_path: 'src/DataFixtures/ORM' # Path to which to look for fixtures relative to the project directory or the bundle path.
    root_dirs:
        - '%kernel.root_dir%'
        - '%kernel.project_dir%'
